create database MY_RUNNING_SHOES;
use MY_RUNNING_SHOES;

CREATE TABLE IF NOT EXISTS USER (id INT NOT NULL AUTO_INCREMENT  PRIMARY KEY, 
    first_name CHAR(30)  NOT NULL, 
    last_name CHAR(30)  NOT NULL,
	 password CHAR(30)  NOT NULL) ENGINE=InnoDB;
	 
CREATE TABLE IF NOT EXISTS SHOE ( id INT NOT NULL AUTO_INCREMENT  PRIMARY KEY, 
    make CHAR(30)  NOT NULL, 
   model CHAR(30) NOT NULL, 
   YEAR year) ENGINE=InnoDB;
 
 CREATE TABLE IF NOT EXISTS USER_SHOES (id INT  NOT NULL AUTO_INCREMENT  PRIMARY KEY, 
     user_id INT NOT NULL,
	 shoe_id INT NOT NULL,
     FOREIGN KEY (user_id) REFERENCES USER(id)   ON UPDATE CASCADE
     ON DELETE RESTRICT, 
     FOREIGN KEY (shoe_id) REFERENCES SHOE(id)   ON UPDATE CASCADE
     ON DELETE RESTRICT, 
     date_purchased DATE , miles INTEGER , is_active TINYINT ) ENGINE=InnoDB;
